@extends("layouts.base")

<!-- Head -->
@section("title","Home")
@section("meta_desc","This is the description.")
@section("meta_author","I am the author.")

@push("styles")
    @vite(["resources/css/main.css",])
@endpush

@push("scripts")
@endpush
<!-- End Head -->



<!-- Header -->
@section("header")
@endsection
<!-- End Header -->



<!-- Main -->
@section("main")
    <h1>Introduction to Laravel Framework</h1>
    <section>
        <h2>1. What is Laravel?</h2>
        <p>
            Laravel is a modern PHP framework built to simplify and enhance web development.
            Created by Taylor Otwell in 2011, it follows the MVC (Model-View-Controller) architectural pattern
            and aims to provide developers with a clean, elegant syntax. Laravel abstracts many of the common tasks
            in web development such as routing, sessions, authentication, and caching, allowing developers to focus on building powerful features
            instead of reinventing the wheel.
        </p>
    </section>

    <section>
        <h2>2. Key Features</h2>
        <p>
            Laravel boasts a wide range of features that streamline application development:
        </p>
        <ul>
            <li><strong>Eloquent ORM:</strong> A beautiful and fluent ActiveRecord implementation for database interaction.</li>
            <li><strong>Blade Template Engine:</strong> A powerful templating engine that allows for clean and readable UI code.</li>
            <li><strong>Artisan Console:</strong> A command-line interface for automating repetitive tasks like migrations and testing.</li>
            <li><strong>Routing System:</strong> Laravel offers expressive and simple-to-use routing declarations, including route groups and middleware.</li>
            <li><strong>Authentication & Authorization:</strong> Built-in mechanisms for login, registration, password reset, and user permissions.</li>
            <li><strong>Task Scheduling:</strong> Automate repetitive tasks using cron jobs with a fluent interface.</li>
            <li><strong>Laravel Mix:</strong> Simplifies asset compilation using Webpack for modern front-end workflows.</li>
        </ul>
    </section>

    <section>
        <h2>3. MVC Architecture</h2>
        <p>
            Laravel’s adoption of MVC provides a clear separation between logic (Model), UI (View), and user interaction (Controller).
            This promotes organized, maintainable, and scalable code. The Model layer uses Eloquent ORM to interact with the database,
            Controllers handle HTTP requests and business logic, while Views display the data.
        </p>
    </section>

    <section>
        <h2>4. Ecosystem and Tools</h2>
        <p>
            Laravel’s ecosystem includes a suite of tools and packages that enrich the development experience:
        </p>
        <ul>
            <li><strong>Laravel Jetstream & Breeze:</strong> Starter kits for authentication scaffolding.</li>
            <li><strong>Laravel Sanctum & Passport:</strong> APIs for token-based authentication (SPA and OAuth).</li>
            <li><strong>Laravel Livewire:</strong> Build dynamic interfaces directly in Blade using PHP.</li>
            <li><strong>Laravel Nova:</strong> An elegant admin panel tool for internal dashboards and administration.</li>
            <li><strong>Laravel Forge & Vapor:</strong> Services for deploying and managing Laravel applications in the cloud.</li>
        </ul>
    </section>

    <section>
        <h2>5. Community and Support</h2>
        <p>
            Laravel has a thriving community and an ecosystem of packages that make it extremely versatile. With official documentation,
            Laracasts tutorials, forums, and GitHub contributions, Laravel continues to evolve and stay at the forefront of PHP development.
            Thousands of open-source packages are available, and regular conferences and meetups help keep the community engaged.
        </p>
    </section>

    <section>
        <h2>6. Why Choose Laravel?</h2>
        <p>
            Laravel is often the first choice for PHP developers due to its:
        </p>
        <ul>
            <li>Clean and expressive syntax</li>
            <li>Rapid application development tools</li>
            <li>Strong community and documentation</li>
            <li>Focus on security and best practices</li>
        </ul>
        <p>
            Laravel helps developers write less code while achieving more, which leads to faster delivery of robust and modern applications.
        </p>
    </section>

    <section>
        <h3>References</h3>
        <p>
            <strong>This text was generated by AI as an example text, double check the info written here.</strong>
            Source: <a href="https://laravel.com" target="_blank" rel="noopener noreferrer">Official Laravel Documentation</a>
        </p>
    </section>
@endsection
<!-- End Main -->


<!-- Footer -->
@section("footer")
@endsection
<!-- End Main -->
